site_name: APEBench
site_description: A Benchmark for Autoregressive PDE Emulators in JAX.
site_author: Felix Koehler
site_url: https://fkoehler.site/apebench

repo_url: https://github.com/Ceyron/apebench
repo_name: Ceyron/apebench
edit_uri: ""  # No edit button, as some of our pages are in /docs and some in /examples via symlink, so it's impossible for them all to be accurate

theme:
    name: material
    features:
        - navigation.sections  # Sections are included in the navigation on the left.
        - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
        - header.autohide  # header disappears as you scroll
    palette:
        - scheme: default
          primary: indigo
          accent: amber
          toggle:
             icon: material/weather-night
             name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: amber
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
    icon:
        repo: fontawesome/brands/github  # GitHub logo in top right
    logo: imgs/apebench_favicon.png
    favicon: "imgs/apebench_favicon.png"

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/felix_m_koehler
    - icon: fontawesome/brands/github
      link: https://github.com/ceyron
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@MachineLearningSimulation


strict: true  # Don't allow warnings during the build process

markdown_extensions:
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4
    - pymdownx.arithmatex:
        generic: true

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search  # default search plugin; needs manually re-enabling when using any other plugins
    - autorefs  # Cross-links to headings
    - mknotebooks  # Jupyter notebooks
    - mkdocstrings:
        handlers:
            python:
                options:
                    inherited_members: true  # Allow looking up inherited methods
                    show_root_heading: true  # actually display anything at all...
                    show_root_full_path: true  # display "diffrax.asdf" not just "asdf"
                    show_if_no_docstring: true
                    show_signature_annotations: true
                    separate_signature: true
                    show_source: true  # don't include source code
                    members_order: source  # order methods according to their order of definition in the source code, not alphabetical order
                    heading_level: 4
                    show_symbol_type_heading: true
                    docstring_style: null

nav:
    - 'index.md'
    - 'typical_workflow.md'
    - 'use_cases.md'
    - 'extending_apebench.md'
    - 'using_cli.md'
    - Examples:
        - Introductory:
            - Simple Advection 1D Emulation: 'examples/simple_advection_1d_learning.ipynb'
            - Scrape Datasets: 'examples/scrape_datasets.ipynb'
            - Animate Learning 1D Burgers: 'examples/animate_emulator_learning_burgers.ipynb'
            - Extending Components: 'examples/component_extensions.ipynb'
        - Advanced:
            - Randomness & Reproducibility: 'examples/sources_of_randomness_and_reproducibility.ipynb'
        - Studies:
            - Unrolled Training for high Difficulty: 'studies/unrolled_training_for_high_difficulty.ipynb'
            - Performance across Metrics: 'studies/performance_across_metrics.ipynb'
            - Difficulty & Receptive Field in 1D Advection: 'studies/difficulty_and_receptive_field_advection_1d.ipynb'
    - Scenarios:
        - Overview: 'api/scenarios/overview.md'
        - Base Scenario: 'api/scenarios/base.md'
        - Difficulty:
            - Linear: 'api/scenarios/difficulty/linear.md'
            - Nonlinear: 'api/scenarios/difficulty/nonlinear.md'
            - Reaction-Diffusion: 'api/scenarios/difficulty/react.md'
            - Generic: 'api/scenarios/difficulty/generic.md'
        - Physical:
            - Linear: 'api/scenarios/physical/linear.md'
            - Nonlinear: 'api/scenarios/physical/nonlinear.md'
            - Reaction-Diffusion: 'api/scenarios/physical/react.md'
            - Navier-Stokes: 'api/scenarios/physical/navier_stokes.md'
            - Linear (Special): 'api/scenarios/physical/linear_special.md'
            - Generic: 'api/scenarios/physical/generic.md'
            - Poisson: 'api/scenarios/physical/poisson.md'
        - Normalized:
            - Linear: 'api/scenarios/normalized/linear.md'
            - Nonlinear: 'api/scenarios/normalized/nonlinear.md'
            - Reaction-Diffusion: 'api/scenarios/normalized/react.md'
            - Generic: 'api/scenarios/normalized/generic.md'
    - API:
        - Run:
            - One Experiment: 'api/run/one_experiment.md'
            - Study: 'api/run/study.md'
        - Postprocess:
            - High Level: 'api/postprocess/high_level.md'
            - Low Level: 'api/postprocess/low_level.md'
            - Dataframe Manipulation: 'api/postprocess/dataframe_manipulation.md'
        - Scrape:
            - Utilities: 'api/scrape/utilities.md'
            - Curations: 'api/scrape/curations.md'
        - 'api/utils.md'
    - Misc:
        - FAQ: 'misc/faq.md'
        - Tips & Tricks: 'misc/tips.md'
        - Gotchas: 'misc/gotchas.md'
